## Learn About Numpy:-

In [3]:
import numpy as np

In [4]:
import pandas as pd


### Creating array form list:-

In [19]:
arr_1d = np.array([1,2,3])
print("1D array:-",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array:-",arr_2d)

1D array:- [1 2 3]
2d array:- [[1 2 3]
 [4 5 6]]


### Different Array creation:-

In [18]:
zeros = np.zeros((3,4))
print("Zero Array:-\n",zeros)

ones = np.ones((2,4))
print("Ones:-", ones)

full = np.full((2,3),5)
print("Fulls:-",full)

random = np.random.random((2,3))
print("random Array:-\n",random)

sequence = np.arange(0,10,2) # range() type
print("Sequence array:-\n",sequence)

Zero Array:-
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:- [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Fulls:- [[5 5 5]
 [5 5 5]]
random Array:-
 [[0.16113684 0.13808859 0.35110833]
 [0.09592409 0.71003246 0.99857601]]
Sequence array:-
 [0 2 4 6 8]


### Vector,Marix,Scaler(constant) and Tensor:-

In [17]:
vector = np.array([1,2,3])
print("vector:- \n",vector)  # 1d Array

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix:- \n",matrix)  # 2d Array

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor:-\n",tensor)   # Multidimention Array

vector:- 
 [1 2 3]
Matrix:- 
 [[1 2 3]
 [4 5 6]]
Tensor:-
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties :-

In [22]:
arr = np.array([[1,2,3],
                [5,6,7],
                [7,8,9]])
print("Shape:-",arr.shape)
print("Dimension :-",arr.ndim)
print("Size :-",arr.size)
print("DType :-",arr.dtype)


Shape:- (3, 3)
Dimension :- 2
Size :- 9
DType :- int64


### Array Reshaping :-

In [ ]:
arr = np.arange(12)
print("Original Array :-",arr)

reshaped = arr.reshape((4,3))
print("Reshaped Array :-\n",reshaped)

flattend = reshaped.flatten() # return New Copy
print("Flattened Array :-",flattend)

raveled = reshaped.ravel()  # Returns View, instead of copy
print("Raveled Array :- ",raveled)
 
transpose = reshaped.T # convert row to column 
print("Trasnposed Array :-\n",transpose)

Original Array :- [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array :-
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Flattened Array :- [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array :-  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Trasnposed Array :-
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
