In [1]:
import pandas as pd
import numpy as np

In [30]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.diag(arr)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
num = np.arange(10)
num

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
i = np.full((3,3),0)
i

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
ar = np.arange(12)
ar
ar.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
even = np.where(ar % 2 == 0)
ev = (lambda x: x % 2 == 0)(arr)
print(ev)

[[False  True False]
 [ True False  True]
 [False  True False]]


In [5]:
arr[:,1]

array([2, 5, 8])

In [7]:
arr[1][1] = 0
arr

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [3]:
df = pd.read_csv('./data/coffee.csv')
df.shape
df.index.to_list()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [13]:
df
coffee = df.copy()

In [15]:
coffee.sort_values('Units Sold')
coffee.loc[[2,3,4],'Units Sold'] = np.nan

In [16]:
coffee

Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        15.0
2     Tuesday    Espresso         NaN
3     Tuesday       Latte         NaN
4   Wednesday    Espresso         NaN
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [19]:
coffee.dropna()

Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        15.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [21]:
coffee[['total_bill','Tip']] = 23

In [23]:
coffee['total_bill'] = coffee['Units Sold'] * 5

In [26]:
coffee[coffee['total_bill'] > 200]

Day Coffee Type  Units Sold  total_bill  Tip
8     Friday    Espresso        45.0       225.0   23
10  Saturday    Espresso        45.0       225.0   23
12    Sunday    Espresso        45.0       225.0   23